"""Export flagged items for manual review."""

from __future__ import annotations

import json
import shlex
from pathlib import Path
from typing import Any, Literal
from urllib.parse import urlparse

import yaml
from sqlmodel import Session, select

from orbis.storage.db import FlaggedItem, open_db

FlaggedExportFormat = Literal["curl", "http", "postman", "yaml"]
SUPPORTED_FLAGGED_FORMATS = {"curl", "http", "postman", "yaml"}


def load_flagged_items(
    db_path: str | Path,
    *,
    kind: str | None = None,
    scan_id: int | None = None,
) -> list[FlaggedItem]:
    engine = open_db(db_path)
    with Session(engine) as session:
        statement = select(FlaggedItem)
        if kind is not None:
            statement = statement.where(FlaggedItem.flag_kind == kind)
        if scan_id is not None:
            statement = statement.where(FlaggedItem.scan_id == scan_id)
        return list(session.exec(statement.order_by(FlaggedItem.id)).all())


def render_flagged_items(
    items: list[FlaggedItem],
    export_format: str,
) -> str:
    normalized = export_format.lower()
    if normalized == "yaml":
        return render_yaml(items)
    if normalized == "curl":
        return render_curl(items)
    if normalized == "http":
        return render_http(items)
    if normalized == "postman":
        return render_postman(items)
    raise ValueError(
        f"unsupported flagged export format {export_format!r}; "
        f"expected one of {', '.join(sorted(SUPPORTED_FLAGGED_FORMATS))}",
    )


def render_yaml(items: list[FlaggedItem]) -> str:
    return yaml.safe_dump(
        [flagged_item_to_dict(item) for item in items],
        sort_keys=False,
        allow_unicode=True,
    )


def render_curl(items: list[FlaggedItem]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by orbis flagged",
        "# Items detected but not automatically tested. Review manually.",
        "",
    ]
    for item in items:
        lines.extend(_comment_block(item))
        if not item.url:
            lines.extend(["# No URL available for this item.", ""])
            continue
        method = (item.method or "GET").upper()
        cookie, warning = _cookie_header(item.auth_state_path, item.url)
        if warning:
            lines.append(f"# WARNING: {warning}")
        if cookie:
            lines.append(f"curl -X {shlex.quote(method)} {shlex.quote(item.url)} \\")
            lines.append(f"  -H {shlex.quote('Cookie: ' + cookie)}")
        else:
            lines.append(f"curl -X {shlex.quote(method)} {shlex.quote(item.url)}")
            lines.append("  # Add auth headers manually if needed.")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_http(items: list[FlaggedItem]) -> str:
    lines: list[str] = []
    for item in items:
        lines.extend(_comment_block(item, marker="#"))
        if not item.url:
            lines.extend(["# No URL available for this item.", ""])
            continue
        method = (item.method or "GET").upper()
        lines.append(f"{method} {item.url}")
        cookie, warning = _cookie_header(item.auth_state_path, item.url)
        if warning:
            lines.append(f"# WARNING: {warning}")
        if cookie:
            lines.append(f"Cookie: {cookie}")
        lines.append("")
        lines.append("###")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_postman(items: list[FlaggedItem]) -> str:
    collection = {
        "info": {
            "name": "orbis flagged items",
            "schema": (
                "https://schema.getpostman.com/json/collection/v2.1.0/"
                "collection.json"
            ),
        },
        "item": [
            _postman_item(item)
            for item in items
            if item.url
        ],
    }
    return json.dumps(collection, ensure_ascii=False, indent=2) + "\n"


def flagged_item_to_dict(item: FlaggedItem) -> dict[str, Any]:
    return {
        "id": item.id,
        "scan_id": item.scan_id,
        "flag_kind": item.flag_kind,
        "item_kind": item.item_kind,
        "method": item.method,
        "url": item.url,
        "description": item.description,
        "page_url": item.page_url,
        "context": _json_or_raw(item.context_json),
        "auth_state_path": item.auth_state_path,
        "timestamp": item.timestamp.isoformat() if item.timestamp else None,
    }


def _comment_block(item: FlaggedItem, marker: str = "#") -> list[str]:
    lines = [
        f"{marker} ----------------------------------------",
        f"{marker} [{item.flag_kind}] {item.description or item.item_kind or 'flagged item'}",
    ]
    if item.page_url:
        lines.append(f"{marker} Page: {item.page_url}")
    if item.auth_state_path:
        lines.append(f"{marker} Auth: {item.auth_state_path}")
    if item.url:
        lines.append(f"{marker} URL: {item.method or 'GET'} {item.url}")
    lines.append(f"{marker} ----------------------------------------")
    return lines


def _postman_item(item: FlaggedItem) -> dict[str, Any]:
    assert item.url is not None
    parsed = urlparse(item.url)
    headers = []
    cookie, warning = _cookie_header(item.auth_state_path, item.url)
    if cookie:
        headers.append({"key": "Cookie", "value": cookie})
    description = flagged_item_to_dict(item)
    if warning:
        description["cookie_warning"] = warning
    return {
        "name": item.description or item.url,
        "request": {
            "method": (item.method or "GET").upper(),
            "header": headers,
            "url": {
                "raw": item.url,
                "protocol": parsed.scheme,
                "host": parsed.hostname.split(".") if parsed.hostname else [],
                "path": [part for part in parsed.path.split("/") if part],
                "query": _postman_query(parsed.query),
            },
            "description": json.dumps(
                description,
                ensure_ascii=False,
                indent=2,
            ),
        },
    }


def _postman_query(query: str) -> list[dict[str, str]]:
    if not query:
        return []
    pairs = []
    for chunk in query.split("&"):
        if "=" in chunk:
            key, value = chunk.split("=", 1)
        else:
            key, value = chunk, ""
        pairs.append({"key": key, "value": value})
    return pairs


def _cookie_header(
    auth_state_path: str | None,
    url: str,
) -> tuple[str | None, str | None]:
    if not auth_state_path:
        return None, None
    try:
        data = json.loads(Path(auth_state_path).read_text(encoding="utf-8"))
    except Exception as exc:
        return None, f"could not load storage_state cookies from {auth_state_path}: {exc}"
    cookies = data.get("cookies")
    if not isinstance(cookies, list):
        return None, f"storage_state has no cookies array: {auth_state_path}"
    host = urlparse(url).hostname or ""
    values = []
    for cookie in cookies:
        if not isinstance(cookie, dict):
            continue
        if not _cookie_matches_host(str(cookie.get("domain") or ""), host):
            continue
        name = cookie.get("name")
        value = cookie.get("value")
        if name is None or value is None:
            continue
        values.append(f"{name}={value}")
    return ("; ".join(values) if values else None), None


def _cookie_matches_host(domain: str, host: str) -> bool:
    normalized = domain.lstrip(".")
    return host == normalized or host.endswith("." + normalized)


def _json_or_raw(value: str | None) -> Any:
    if value is None:
        return None
    try:
        return json.loads(value)
    except Exception:
        return value
